name: CD
on:
  push:
    branches: [ "main" , "orm-database" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ~/apps/testdeployment
            git pull origin orm-database
            git status
            npm install --omit=dev
            cd src
            npx prisma init
            npx prisma migrate dev
            pm2 restart main.js
